export declare const FPS_TO_MS = 0.3048;
export declare const MS_TO_FPS: number;
export declare const INCH_TO_CM = 2.54;
export declare const YARD_TO_M = 0.9144;
export declare const MPH_TO_MS = 0.44704;
export declare const HPA_TO_INHG = 0.029529983071445;
export declare const KG_M3_TO_LB_FT3 = 0.0624279605761;
export declare function fpsToMs(value: number): number;
export declare function msToFps(value: number): number;
export declare function inchToCm(value: number): number;
export declare function cmToInch(value: number): number;
export declare function yardToM(value: number): number;
export declare function mToYard(value: number): number;
export declare function mphToMs(value: number): number;
export declare function msToMph(value: number): number;
export declare function hPaToInHg(value: number): number;
export declare function inHgToHPa(value: number): number;
export declare function kgM3ToLbFt3(value: number): number;
export declare function roundTo(value: number, decimals?: number): number;
export declare function cmToMrad(cm: number, distanceM: number): number;
export declare function cmToMoa(cm: number, distanceM: number): number;
export declare function formatSigned(value: number, decimals?: number): string;
