import type { BarrelVelocityPoint, TrajectoryPoint } from "./core/types.js";
import { mToYard, msToFps } from "./core/units.js";
declare const I18N: {
    readonly sv: {
        readonly appEyebrow: "KÄLLSPÅRAD BALLISTIK";
        readonly title: "BULLET DROP";
        readonly titleSub: "REFERENSGUIDE";
        readonly subtitle: "Kulfall & vindavdrift med explicit datakvalitet, källor och osäkerhetsklassning.";
        readonly atmosphere: "ATMOSFÄR";
        readonly language: "Språk";
        readonly units: "Enheter";
        readonly metric: "Metrisk";
        readonly imperial: "Imperial";
        readonly theme: "Tema";
        readonly light: "Ljust";
        readonly dark: "Mörkt";
        readonly system: "System";
        readonly load: "Laddning";
        readonly zero: "Nollning";
        readonly sightHeight: "Sikthöjd över pipa";
        readonly sightPresets: "Snabbval sikthöjd";
        readonly pistol: "Pistol";
        readonly scope: "Kikare";
        readonly arIrons: "AR-järn";
        readonly temperature: "Temperatur";
        readonly pressure: "Lufttryck";
        readonly wind: "Vind";
        readonly windAngle: "Vindvinkel";
        readonly calculatedData: "■ BERÄKNAD DATA";
        readonly calculatedHelp: "Kulfall relativt siktlinje. Nollningskolumnen markeras med ◉.";
        readonly showLinear: "Visa linjärt";
        readonly showAngular: "Visa vinkel";
        readonly barrel: "Pipa";
        readonly source: "Källa";
        readonly windDrift: "■ VINDAVDRIFT";
        readonly windHelpPrefix: "Approximation via lag-regel";
        readonly selected: "VALD RAD";
        readonly showSources: "Visa källor";
        readonly dataQuality: "Datakvalitet";
        readonly nominalMv: "Nominal MV";
        readonly bc: "BC";
        readonly barrelData: "Pipdata";
        readonly publishedMeasured: "publicerad/mätt";
        readonly sourcesForLoad: "Källor för vald laddning";
        readonly comments: "Kommentarer";
        readonly muzzleVelocity: "Utgångshastighet — vald laddning";
        readonly mvHelp: "Varje rad visar metod och källklassning.";
        readonly cribCard: "SNABBKORT";
        readonly print: "Skriv ut";
        readonly notes: "OBSERVERA";
        readonly sourceCatalog: "Källkatalog";
        readonly catalogText: "källposter finns i datamodellen. Endast relevanta källor för vald laddning visas öppet ovan.";
        readonly footerLeft: "G1 numerisk integration · spårbar data";
        readonly footerRight: "tacticaljunkyard.com";
        readonly note1: "Kulfall beräknas relativt siktlinje med sikthöjd och vald nollning.";
        readonly note2: "G1-drag använder numerisk integration; vind är separat approximation via lag-regel.";
        readonly note3: "Temperatur påverkar både lufttäthet och ljudhastighet/Mach.";
        readonly note4: "Alla piplängdsvärden ska verifieras med din ammunition, ditt vapen och din nollning.";
        readonly high: "Hög";
        readonly medium: "Medel";
        readonly limited: "Begränsad";
        readonly low: "Låg";
        readonly highDetail: "Majoriteten av kritiska värden har tillverkar- eller mätt källa.";
        readonly mediumDetail: "Blandning av mätta, publicerade och härledda värden.";
        readonly limitedDetail: "Flera viktiga värden är härledda och bör verifieras.";
        readonly lowDetail: "Estimat dominerar; använd främst som struktur/referens.";
        readonly manufacturer: "Tillverkare";
        readonly measured: "Mätt 3:e part";
        readonly derived: "Härledd";
        readonly estimate: "Estimat";
        readonly noWind: "Medvind/motvind";
        readonly halfWind: "Half value";
        readonly fullWind: "Full value";
        readonly localWeather: "Platsväder";
        readonly useLocalWeather: "Hämta platsväder";
        readonly weatherIdle: "ISA-standard används tills platsväder hämtas.";
        readonly weatherLoading: "Hämtar position och väder…";
        readonly weatherReady: "Platsväder används";
        readonly weatherDenied: "Platsåtkomst nekades — manuella värden används.";
        readonly weatherUnavailable: "Platsväder är inte tillgängligt i denna webbläsare.";
        readonly weatherError: "Kunde inte hämta platsväder — manuella värden används.";
        readonly weatherSource: "Open-Meteo";
        readonly updateReadyTitle: "Ny version finns";
        readonly updateReadyText: "Sidan har hämtat en ny version. Ladda om för att använda senaste data och kod.";
        readonly updateReload: "Ladda om";
        readonly updateLater: "Senare";
    };
    readonly en: {
        readonly appEyebrow: "SOURCE-TRACKED BALLISTICS";
        readonly title: "BULLET DROP";
        readonly titleSub: "REFERENCE GUIDE";
        readonly subtitle: "Bullet drop and wind drift with explicit data quality, sources and uncertainty classification.";
        readonly atmosphere: "ATMOSPHERE";
        readonly language: "Language";
        readonly units: "Units";
        readonly metric: "Metric";
        readonly imperial: "Imperial";
        readonly theme: "Theme";
        readonly light: "Light";
        readonly dark: "Dark";
        readonly system: "System";
        readonly load: "Load";
        readonly zero: "Zero";
        readonly sightHeight: "Sight height above bore";
        readonly sightPresets: "Sight height presets";
        readonly pistol: "Pistol";
        readonly scope: "Scope";
        readonly arIrons: "AR irons";
        readonly temperature: "Temperature";
        readonly pressure: "Pressure";
        readonly wind: "Wind";
        readonly windAngle: "Wind angle";
        readonly calculatedData: "■ CALCULATED DATA";
        readonly calculatedHelp: "Drop relative to line of sight. The zero column is marked with ◉.";
        readonly showLinear: "Show linear";
        readonly showAngular: "Show angular";
        readonly barrel: "Barrel";
        readonly source: "Source";
        readonly windDrift: "■ WIND DRIFT";
        readonly windHelpPrefix: "Lag-rule approximation";
        readonly selected: "SELECTED ROW";
        readonly showSources: "Show sources";
        readonly dataQuality: "Data quality";
        readonly nominalMv: "Nominal MV";
        readonly bc: "BC";
        readonly barrelData: "Barrel data";
        readonly publishedMeasured: "published/measured";
        readonly sourcesForLoad: "Sources for selected load";
        readonly comments: "Comments";
        readonly muzzleVelocity: "Muzzle velocity — selected load";
        readonly mvHelp: "Each row shows method and source confidence.";
        readonly cribCard: "CRIB CARD";
        readonly print: "Print";
        readonly notes: "NOTES";
        readonly sourceCatalog: "Source catalog";
        readonly catalogText: "source records exist in the data model. Only selected-load sources are expanded above.";
        readonly footerLeft: "G1 numerical integration · traceable data";
        readonly footerRight: "tacticaljunkyard.com";
        readonly note1: "Drop is calculated relative to line of sight with sight height and selected zero.";
        readonly note2: "G1 drag uses numerical integration; wind is a separate lag-rule approximation.";
        readonly note3: "Temperature affects both air density and speed of sound/Mach.";
        readonly note4: "Always verify barrel-length values with your ammunition, firearm and zero.";
        readonly high: "High";
        readonly medium: "Medium";
        readonly limited: "Limited";
        readonly low: "Low";
        readonly highDetail: "Most critical values have manufacturer or measured sources.";
        readonly mediumDetail: "Mixed measured, published and derived values.";
        readonly limitedDetail: "Several important values are derived and should be verified.";
        readonly lowDetail: "Estimates dominate; use primarily as structure/reference.";
        readonly manufacturer: "Manufacturer";
        readonly measured: "Measured 3rd party";
        readonly derived: "Derived";
        readonly estimate: "Estimate";
        readonly noWind: "Tail/head wind";
        readonly halfWind: "Half value";
        readonly fullWind: "Full value";
        readonly localWeather: "Local weather";
        readonly useLocalWeather: "Use local weather";
        readonly weatherIdle: "ISA standard is used until local weather is loaded.";
        readonly weatherLoading: "Getting position and weather…";
        readonly weatherReady: "Local weather is active";
        readonly weatherDenied: "Location access denied — manual values are used.";
        readonly weatherUnavailable: "Local weather is not available in this browser.";
        readonly weatherError: "Could not load local weather — manual values are used.";
        readonly weatherSource: "Open-Meteo";
        readonly updateReadyTitle: "New version available";
        readonly updateReadyText: "The page has downloaded a new version. Reload to use the latest data and code.";
        readonly updateReload: "Reload";
        readonly updateLater: "Later";
    };
};
type Language = keyof typeof I18N;
type ThemeMode = "light" | "dark" | "system";
type UnitSystem = "metric" | "imperial";
type WindOptionId = "no" | "half" | "full";
type WeatherStatus = "idle" | "loading" | "ready" | "denied" | "unavailable" | "error";
type State = {
    language: Language;
    unitSystem: UnitSystem;
    themeMode: ThemeMode;
    systemDark: boolean;
    caliberId: string;
    loadId: string;
    zeroM: number;
    sightHeightCm: number;
    temperatureC: number;
    pressureHPa: number;
    windSpeedMs: number;
    windOptionId: WindOptionId;
    showAngular: boolean;
    weatherStatus: WeatherStatus;
    weatherMessage: string | null;
    updateReady: boolean;
};
type BarrelCalculation = {
    barrel: BarrelVelocityPoint;
    points: TrajectoryPoint[];
};
declare function calculateForSelectedLoad(): BarrelCalculation[];
export declare const __appVersion = "1.4.5";
export declare const __defaultState: State;
export declare const __calculateForSelectedLoad: typeof calculateForSelectedLoad;
export declare const __msToFps: typeof msToFps;
export declare const __mToYard: typeof mToYard;
export {};
